import {
  CENTRAL_ADMIN,
  PARENT,
  SCHOOL_ADMIN,
  STUDENT,
  TEACHER,
} from "@/lib/roles";


export const menuItems = [ 
  {
    title: "MENU",
    items: [
      {
        icon: "/super-admin.png",
        label: "Super Admin",
        href: "/superadmin",
        visible: [CENTRAL_ADMIN],
      },
      {
        icon: "/home.png",
        label: "Home",
        href: "/admin",
        visible: [SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
      },
      {
        icon: "/teacher.png",
        label: "Teachers",
        href: "/list/teachers",
        // visible: ["admin", "teacher"],
        visible: [SCHOOL_ADMIN, TEACHER],
      },
      {
        icon: "/student.png",
        label: "Students",
        href: "/list/students",
        // visible: ["admin", "teacher"],
        visible: [SCHOOL_ADMIN, TEACHER],
      },
      {
        icon: "/parent.png",
        label: "Parents",
        href: "/list/parents",
        // visible: ["admin", "teacher"],
        visible: [SCHOOL_ADMIN, TEACHER],
      },
      {
        icon: "/subject.png",
        label: "Subjects",
        href: "/list/subjects",
        // visible: ["admin"],
        visible: [SCHOOL_ADMIN],
      },
      {
        icon: "/class.png",
        label: "Classes",
        href: "/list/classes",
        // visible: ["admin", "teacher"],
        visible: [SCHOOL_ADMIN, TEACHER],
      },
      {
        icon: "/lesson.png",
        label: "Lessons",
        href: "/list/lessons",
        // visible: ["admin", "teacher"],
        visible: [SCHOOL_ADMIN, TEACHER],
      },
      {
        icon: "/exam.png",
        label: "Exams",
        href: "/list/exams",
        // visible: ["admin", "teacher", "student", "parent"],
        visible: [SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
      },
      {
        icon: "/attendance.png",
        label: "Attendance",
        href: "/list/attendance",
        // visible: ["admin", "teacher", "student", "parent"],
        visible: [SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
        nested: [
          {
            icon: "/student-attendance.png",
            label: "Student Attendance",
            href: "/list/attendance/student-attendance",
            // visible: ["admin"],
            visible: [SCHOOL_ADMIN],
          },
          {
            icon: "/attendance-3.png",
            label: "Teacher Attendance",
            href: "/list/attendance/teacher-attendance",
            // visible: ["admin"],
            visible: [SCHOOL_ADMIN],
          },
          {
            icon: "/attendance-summary-1.webp",
            label: "Attendance Summary",
            href: "/list/attendance/attendance-summary",
            // visible: ["admin"],
            visible: [SCHOOL_ADMIN],
          },
        ],
      },
      {
        icon: "/assignment.png",
        label: "Assignments",
        href: "/list/assignments",
        // visible: ["admin", "teacher", "student", "parent"],
        visible: [SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
      },
      {
        icon: "/result.png",
        label: "Results",
        href: "/list/results",
        // visible: ["admin", "teacher", "student", "parent"],
        visible: [SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
      },

      {
        icon: "/accounting.png",
        label: "Accounting",
        href: "/list/accounting",
        // visible: ["admin"],
        visible: [SCHOOL_ADMIN],
        nested: [
          {
            icon: "/fees.png",
            label: "Fees Collection",
            href: "/list/accounting/fees-collection",
            // visible: ["admin"],
            visible: [SCHOOL_ADMIN],
          },
          {
            icon: "/expense.png",
            label: "Expenses",
            href: "/list/accounting/expenses",
            // visible: ["admin"],
            visible: [SCHOOL_ADMIN],
          },
          {
            icon: "/fee-type.png",
            label: "Fee Type",
            href: "/list/accounting/fee-type",
            // visible: ["admin"],
            visible: [SCHOOL_ADMIN],
          },
          {
            icon: "/summary.png",
            label: "Summary",
            href: "/list/accounting/fees-summary",
            // visible: ["admin"],
            visible: [SCHOOL_ADMIN],
          },
        ],
      },
      {
        icon: "/calendar.png",
        label: "Events",
        href: "/list/events",
        // visible: ["admin", "teacher", "student", "parent"],
        visible: [SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
      },
      {
        icon: "/id-card.png",
        label: "Card Generator",
        href: "/list/card-generator",
        // visible: ["admin", "teacher", "student", "parent"],
        visible: [SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
        nested: [
          {
            icon: "/student-card.png",
            label: "Student ID Card",
            href: "/list/card-generator/student-id-card",
            // visible: ["admin"],
            visible: [SCHOOL_ADMIN],
          },
          {
            icon: "/teacher-id-card.png",
            label: "Teacher ID Card",
            href: "/list/card-generator/teacher-id-card",
            // visible: ["admin"],
            visible: [SCHOOL_ADMIN],
          },
          {
            icon: "/admit-card.png",
            label: "Admit Card",
            href: "/list/card-generator/student-admit-card",
            // visible: ["admin"],
            visible: [SCHOOL_ADMIN],
          },
          {
            icon: "/mark-sheet.webp",
            label: "Mark Sheet",
            href: "/list/card-generator/student-mark-sheet",
            // visible: ["admin"],
            visible: [SCHOOL_ADMIN],
          },
        ],
      },
      {
        icon: "/message.png",
        label: "Messages",
        href: "/list/messages",
        // visible: ["admin", "teacher", "student", "parent"],
        visible: [SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
      },
      {
        icon: "/announcement.png",
        label: "Announcements",
        href: "/list/announcements",
        // visible: ["admin", "teacher", "student", "parent"],
        visible: [SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
      },
      {
        icon: "/web-3.png",
        label: "Website Setting",
        href: "/website-setting",
        // visible: ["admin"],
        visible: [SCHOOL_ADMIN],
      },
    ],
  },
  {
    title: "OTHER",
    items: [
      {
        icon: "/profile.png",
        label: "Profile",
        href: "/profile",
        // visible: ["admin", "teacher", "student", "parent"],
        visible: [SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
      },
      {
        icon: "/setting.png",
        label: "Settings",
        href: "/settings",
        // visible: ["admin", "teacher", "student", "parent"],
        visible: [SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
      },
      {
        icon: "/logout.png",
        label: "Logout",
        href: "/logout",
        // visible: ["admin", "teacher", "student", "parent"],
        visible: [CENTRAL_ADMIN, SCHOOL_ADMIN, TEACHER, STUDENT, PARENT],
      },
    ],
  },
];